formassembly.api.oauth:
  type: config_object
  label: 'FormAssembly API'
  mapping:
    endpoint:
      type: uri
      label: 'FormAssembly API Endpoint'
    admin_index:
      type: boolean
      label: 'Using an admin index'
    credentials:
      type: mapping
      mapping:
        provider:
          type: string
          label: 'Credential provider'
        data:
          type: formassembly.oauth_creds.[%parent.provider]
          label: 'Oauth Key'

formassembly.oauth_creds.formassembly:
  label: 'FormAssembly Oauth Credentials'
  type: mapping
  mapping:
    cid:
      type: string
      label: 'Client ID'
    secret:
      type: string
      label: 'Client Secret'

formassembly.oauth_creds.key:
  type: mapping
  label: 'FormAssembly Oauth Key ID'
  mapping:
    id:
      type: string
      label: 'Key ID'
